USE return_management_db;

CREATE TABLE IF NOT EXISTS temp_return_manifests (
    manifest_id INT AUTO_INCREMENT PRIMARY KEY,
    resi_number VARCHAR(100) NOT NULL,
    no_pesanan VARCHAR(100) NOT NULL,
    customer_name VARCHAR(100) DEFAULT NULL,
    customer_contact VARCHAR(50) DEFAULT NULL,
    source_type VARCHAR(50) DEFAULT NULL,
    return_category VARCHAR(50) DEFAULT NULL,
    return_reason TEXT DEFAULT NULL,
    notes TEXT DEFAULT NULL,
    is_processed TINYINT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    nama_toko VARCHAR(100) DEFAULT NULL,
    metode_pengiriman VARCHAR(100) DEFAULT NULL,
    jenis_pengiriman VARCHAR(100) DEFAULT NULL,
    penerima VARCHAR(100) DEFAULT NULL,
    alamat_pengiriman TEXT DEFAULT NULL,
    waktu_outbound VARCHAR(100) DEFAULT NULL,
    total_harga_pesanan DECIMAL(15, 2) DEFAULT 0.00,
    nama_pemilik VARCHAR(100) DEFAULT NULL,
    waktu_picking VARCHAR(100) DEFAULT NULL,
    admin_pengemasan VARCHAR(100) DEFAULT NULL,
    waktu_packing VARCHAR(100) DEFAULT NULL,
    nomor_daftar VARCHAR(100) DEFAULT NULL,
    no_pesanan_wms VARCHAR(100) DEFAULT NULL,
    no_pesanan_oms VARCHAR(100) DEFAULT NULL,
    status VARCHAR(100) DEFAULT NULL,
    gudang VARCHAR(100) DEFAULT NULL,
    waktu_pesanan VARCHAR(100) DEFAULT NULL,
    batas_waktu_pengiriman VARCHAR(100) DEFAULT NULL,
    waktu_cetak VARCHAR(100) DEFAULT NULL,
    mata_uang VARCHAR(50) DEFAULT NULL,
    tgl DATE DEFAULT NULL,
    kota VARCHAR(100) DEFAULT NULL,
    expedisi VARCHAR(100) DEFAULT NULL,
    UNIQUE INDEX idx_temp_resi_pesanan (resi_number, no_pesanan),
    INDEX idx_temp_resi_number (resi_number),
    INDEX idx_temp_no_pesanan (no_pesanan),
    INDEX idx_temp_is_processed (is_processed)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS temp_return_manifest_items (
    manifest_item_id INT AUTO_INCREMENT PRIMARY KEY,
    manifest_id INT NOT NULL,
    item_code VARCHAR(100) DEFAULT NULL,
    item_name VARCHAR(200) NOT NULL,
    item_description TEXT DEFAULT NULL,
    serial_number VARCHAR(100) DEFAULT NULL,
    batch_number VARCHAR(100) DEFAULT NULL,
    quantity INT NOT NULL DEFAULT 1,
    unit_price DECIMAL(15, 2) DEFAULT 0.00,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    varian_product VARCHAR(100) DEFAULT NULL,
    nomor VARCHAR(50) DEFAULT NULL,
    rak VARCHAR(100) DEFAULT NULL,
    kondisi VARCHAR(50) DEFAULT NULL,
    FOREIGN KEY (manifest_id) REFERENCES temp_return_manifests(manifest_id) ON DELETE CASCADE,
    INDEX idx_temp_manifest_id (manifest_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
